apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasktracker.fullname" . }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.log.level | quote }}

  KAFKA_BROKERS: {{ .Values.kafka.brokers | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  KAFKA_GROUP_ID: {{ .Values.kafka.groupId | quote }}
  KAFKA_CLIENT_ID: {{ .Values.kafka.clientId | quote }}

  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_USERNAME: {{ .Values.database.username | quote }}
  DATABASE_SSLMODE: {{ .Values.database.sslmode | quote }}